### ISSUE TITLE
Switch to Pipenv for packaging

### ISSUE THREAD

**Issue by iKevinY** [ubclaunchpad/minutes#111]
Considering [Pipenv](https://docs.pipenv.org) is the currently the [officially recommended Python packaging tool](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies), and `Pipfile` support will eventually be coming to `pip` directly, it might be a good idea to switch over from Conda now to stay ahead of the curve!

**Comment by chadlagore** [comment]
#107
