### ISSUE TITLE
error while testing a conversation file

### ISSUE THREAD

**Issue by rohithkodali** [ubclaunchpad/minutes#130]
Hi,
   I have been following "minutes" from past few days and observed the transformation from docker to a python library. would soon want to add my own models into this repository.

currently i have an issue when i'm testing the model built and here is the error

conversation = Conversation('test.wav')
TypeError: __init__() missing 1 required positional argument: 'speakers'

do this speakers are the one we added to minutes while training (minutes.add_speakers([])) or do we need to create a separate list and pass that argument to converastion?

**Comment by grig-guz** [comment]
You need to create a list of speakers that you added while training

**Comment by rohithkodali** [comment]
got it thanks a lot.

**Comment by iKevinY** [comment]
Hey @rohithkodali, we're super excited to outside interest in Minutes! We're still deep in the process of transitioning the project into a standalone repository, so the API might go through a lot of changes — just thought I'd give you a heads-up! 😄

**Comment by rohithkodali** [comment]
i always have an eye on this project, hope will add lot of my stuff in this once this migration thing is done.

**Comment by chadlagore** [comment]
:wave: hi @rohithkodali. Closing because it looks like we worked it out :+1:
