### ISSUE TITLE
Find a Labeled Dataset

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/minutes#32]
# Find a Labeled Dataset

+ Find a dataset from Youtube or elsewhere that would come with the speaker labels as described in #30.

**Comment by iKevinY** [comment]
You can visit `https://www.youtube.com/api/timedtext?lang=en&v=<video_id>` to retrieve an XML file of the transcript for a given YouTube video. [`youtube-dl`](https://github.com/rg3/youtube-dl) is a good way to download YouTube videos (you can pass `-x --audio-format mp3`) to download the audio track of a YouTube video.

**Comment by iKevinY** [comment]
Essentially replaced by #33.
