### ISSUE TITLE
Consume XML

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/minutes#34]
# Consume XML

+ From an XML file like this one https://www.youtube.com/api/timedtext?lang=en&v=Xz3btMhdQ6Y (assume it is already downloaded), write a function that will produce a table of labels.
+ **Your function should also take a sample rate as input.**

| 0 | 1  | 2 | 3 | 4 |
|---|----|---|---|---|
| 0 |  0 | 0 | 0 | 1 |
| 0 | 0  | 0 | 0 | 1 |
| 1 | 0  | 0 | 0 | 0 |

where the columns are speaker names (numbers) and there are `S * L` rows.

`S` = the sample rate.
`L` = number of seconds (this is given in the xml)

**Comment by iKevinY** [comment]
Addressed by #45.
