### ISSUE TITLE
Collect list of Youtube IDs

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/minutes#36]
# Collect a List of Youtube IDs

+ Make a list, include the delimiter information.

### Example

```json
[
    {"id":"obgTxz-x33Q", "left_delim": null, "right_delim": ":"}
    {"id":"Mw5T62dJzhQ", "left_delim": "[", "right_delim": "]"}
]
```

**Comment by iKevinY** [comment]
Just to clarify, the delimiter info here is being used to describe the format of how the speaker name appears in the transcript (ex. `Bob: Lorem ipsum` vs. `[Bob] Lorem ipsum`).

**Comment by chadlagore** [comment]
Yes. I think this is enough information to regex the speakers out.
