### ISSUE TITLE
Split testing data

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/minutes#68]
# TODO

+ Split testing data into training, validation and testing sets.
+ Use the cli (`pipeline.py`).

**Comment by grig-guz** [comment]
I did the splitting and removing datapoints where labels are -1 in the jupyter, will add it here later

**Comment by shirleyx2000** [comment]
Is -1 different from silence?

**Comment by chadlagore** [comment]
Yes @shirleyx2000, -1 is unknown.
