### ISSUE TITLE
Feature Specification

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/minutes#7]
# Feature Specification & Clustering

+ What features matter in voice samples?
+ Fourier transform? MFCC? Loudness?
+ Clustering

**Comment by grig-guz** [comment]
## Features to consider

- Magnitude spectrum

(to be updated)

**Comment by shirleyx2000** [comment]
**Prosodic Features**:
      _Disadvantage_ 
      - prone to error if speaker is role playing as someone else, in which identifying features will be completely altered
      - length of observation may produce varying performance as certain characteristics need a longer sample to deduce

      ☐ Pauses
        ☐ unintentional: hesitation/non-fluency feature
        ☐ intentional: period, colons, ssemi-colons, comma

      ☐ Pitch
        ☐ intonation
        ☐ intentional: question mark
        ☐ unintentional: feelings (astonishment, boredom, puzzlement)

      ☐ Stress / emphasis
        ☐ stressed word or syllable, preceded by a very slight pause

      ☐ Diction
        ☐ structure of sentence
        ☐ perhaps require transcription to look at word patterns (NLP!)

      ☐ Volume 
        ☐ certain speakers have a fuller tone 

      ☐ Enunciation
        ☐ clarity of consonants

      ☐ Tempo/Speed
        ☐ e.g. impatience, reflectiveness

**Comment by chadlagore** [comment]
Update: 65-70% accuracy using `python_speech_features` mfcc, logfbank and ssc features.
