### ISSUE TITLE
Implement Transfer Learning

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/minutes#80]
https://en.wikipedia.org/wiki/Transfer_learning

**Comment by grig-guz** [comment]
A short into to the main idea:
https://youtu.be/pA4BsUK3oP4?t=13m10s

**Comment by chadlagore** [comment]
https://towardsdatascience.com/automatic-speaker-recognition-using-transfer-learning-6fab63e34e74

**Comment by grig-guz** [comment]
http://www.openslr.org/12
